### ISSUE TITLE
Fun event finish message uncapitalized.

### ISSUE THREAD

**Issue by heyitsbench** [55Honey/Acore_eventScripts#29]
`The event Battle for [eventname] has ended. See you next time!`

[eventname] is always uncapitalized due to the internal event names being uncapitalized in the script. This causes messages like:
`The event Battle for zangarmarsh has ended. See you next time!`
to appear. Zangarmarsh should be capitalized in this message as it is a proper noun, i.e.:
`The event Battle for Zangarmarsh has ended. See you next time!`

**Comment by 55Honey** [comment]
It requires a converter.

```lua
local function firstToUpper(str)
    return (str:gsub("^%l", string.upper))
end
```

Want to try some Lua?

**Comment by 55Honey** [comment]
Closed in https://github.com/55Honey/Acore_eventScripts/commit/006602dadc0640ec17ea49c30e0b445f077082c5
